name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install capnp dependencies
        run: sudo apt-get install -y capnproto libcapnp-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.85
        with:
          components: clippy

      - name: Clippy check
        run: |
          cargo clippy --manifest-path=stratum-apps/Cargo.toml --all-features -- -D warnings
          cargo clippy --manifest-path=pool-apps/Cargo.toml -- -D warnings
          cargo clippy --manifest-path=pool-apps/jd-server/Cargo.toml -- -D warnings
          cargo clippy --manifest-path=miner-apps/Cargo.toml -- -D warnings
          cargo clippy --manifest-path=miner-apps/mining-device/Cargo.toml -- -D warnings
          cargo clippy --manifest-path=integration-tests/Cargo.toml -- -D warnings
          cargo clippy --manifest-path=bitcoin-core-sv2/Cargo.toml -- -D warnings

  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install capnp dependencies
        run: sudo apt-get install -y capnproto libcapnp-dev

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check formatting
        run: |
          cargo fmt --all --manifest-path=stratum-apps/Cargo.toml -- --check
          cargo fmt --all --manifest-path=pool-apps/Cargo.toml -- --check
          cargo fmt --all --manifest-path=pool-apps/jd-server/Cargo.toml -- --check
          cargo fmt --all --manifest-path=miner-apps/Cargo.toml -- --check
          cargo fmt --all --manifest-path=miner-apps/mining-device/Cargo.toml -- --check
          cargo fmt --all --manifest-path=integration-tests/Cargo.toml -- --check 
          cargo fmt --all --manifest-path=bitcoin-core-sv2/Cargo.toml -- --check

  machete:
    name: Unused Dependencies (cargo machete)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo-machete
        uses: bnjbvr/cargo-machete@main